@startuml
autonumber
'hide footbox
actor "Warehouse Employee" as WE
participant ":UploadFileUI" as UI
participant ":UploadFileController" as CTRL
participant ":UploadFileService" as UFS
participant ":PersistenceContext" as PC
participant ":RepositoryFactory" as RF
participant ":UploadFileRepository" as UFR

activate WE
WE -> UI :  starts set up the warehouse plan
activate UI

UI -> CTRL : getJSONFile()
activate CTRL

CTRL -> UFS : getJSONFile()
activate UFS

UFS -> PC : repositories()
deactivate UFS

activate PC
PC -> RF : JSONFile()
deactivate PC

activate RF
RF -> UFR : warehousePlan()
activate UFR
deactivate UFR

deactivate RF

UFS -> UFR : findWarehousePlan()
activate UFR

UFR --> UFS : allStoragesAreas()
deactivate UFR

UFS --> CTRL

CTRL --> UI

UI --> WE : informs operation success
deactivate UI
deactivate WE

@enduml
