@startuml
autonumber
actor "Warehouse Employee" as WE

activate WE

":System" --> WE : shows dimensions of storage areas
activate ":System"

WE -> ":System" : chooses to open a JSON file
deactivate ":System"

":System" --> WE : opens JSON file
activate ":System"

WE -> ":System" : enter the data of the warehouse plant
deactivate ":System"

WE -> ":System" : closes and save JSON file
activate ":System"

":System" --> WE : informs operation success
deactivate ":System"

deactivate ":System"
deactivate WE

@enduml