@startuml
autonumber
actor "Warehouse Employee" as WE

activate WE

WE -> ":System" : set up the warehouse plant
activate ":System"

":System" --> WE : shows dimensions of storage areas
deactivate ":System"

WE -> ":System" : chooses to open a JSON file
activate ":System"

":System" --> WE : opens JSON file
deactivate ":System"

WE -> ":System" : enter the data of the warehouse plant
activate ":System"

":System" --> WE : shows all data and requests confirmation
deactivate ":System"

WE -> ":System" : closes and save JSON file
activate ":System"

":System" --> WE : informs operation success
deactivate ":System"

deactivate ":System"
deactivate WE

@enduml