@startuml
skinparam classAttributeIconSize 0

class UploadFileUI <<presentation>> {
    +doShow()
}

class UploadFileController <<application>> {
    +uploadFile()
}

class UploadFileRepository <<repository>> {
  +save(JSON File)
}

class UploadFile <<domain>>{
   +uploadFile(JSON File)
   +
}

UploadFileUI -> UploadFileController : theController
UploadFileUI -> UploadFileRepository : repo
UploadFileController -> UploadFile : the JSON File
UploadFileUI ..> UploadFile : the JSON File

@enduml