@startuml
autonumber
'hide footbox
actor "Sales Clerck" as SC
participant ":RegisterTestUI" as UI
participant ":RegisterTestController" as CTRL
participant ":Company" as Company
participant "testStore:TestStore" as Store
participant "cStore:ClientStore" as cStore
participant "calStore:ClinicalAnalysisLaboratoryStore" as calStore
participant "pc :ParameterCategory " as Pc
participant "test : Test" as Test
participant "testTypeStore:TestTypeStore" as ttStore
participant "parameterStore:ParameterStore" as pStore
participant "parameterCategoryStore:ParameterCategoryStore" as pcStore
participant "client : Client" as Client
participant "tt : TestType" as Tt
participant "p : List<Parameter> " as parameterList
participant "calList: List<ClinicalAnalysisLaboratory>" as calList





activate SC
SC -> UI : Starts test registration
activate UI

UI -> CTRL : getClinicalAnalysisLaboratory()
activate CTRL

CTRL -> Company : calStore = getClinicalAnalysisLaboratoryStore()
activate Company
deactivate Company

CTRL -> calStore : calList= getCalList()
activate calStore
deactivate calStore
deactivate CTRL

UI -> CTRL : getClients()

activate CTRL
CTRL -> Company : clientStore = getClientStore()

activate Company
deactivate Company

CTRL -> cStore : clientsList= getClientsList()
activate cStore
deactivate cStore
deactivate CTRL

UI --> SC : Asks to enter citizen card number of the client
deactivate UI
deactivate Company


SC -> UI : Types citizen card number
activate UI

UI -> CTRL : findClient(tin)
activate CTRL

CTRL -> cStore : client = findClient(tin)
deactivate CTRL
activate cStore

UI -> CTRL : getTestTypeList()
deactivate Store
activate CTRL
deactivate cStore

CTRL -> Company : testTypeStore = getTestTypeStore()
activate Company
deactivate Company

CTRL -> ttStore : testTypeList = getTestTypeList()
deactivate CTRL
activate ttStore


UI --> SC  : Shows list of test types
deactivate UI
deactivate Company
deactivate ttStore

SC -> UI : Selects test type
activate UI

UI -> CTRL : getParameterCategoryList()
deactivate Store
activate CTRL

CTRL -> Company : parameterCategoryStore = getParameterCategoryStore()
activate Company
deactivate Company

CTRL -> pcStore : parameterCategoryList = getParameterCategoryList()
deactivate CTRL
activate pcStore


loop until receptionist chooses to exit
UI --> SC  : Shows list of categories
deactivate UI
deactivate Company
deactivate pcStore

SC -> UI : Selects category
activate UI

UI -> CTRL : getParameterList()
deactivate Store
activate CTRL

CTRL -> Company : parameterStore = getParameterStore()
activate Company
deactivate Company

CTRL -> pStore : parameterList = getParameterList()
deactivate CTRL
activate pStore



loop until receptionist chooses to exit

UI --> SC  : Shows list of parameters
deactivate pStore
deactivate UI

deactivate Company


SC -> UI : Selects parameter/s
activate UI

deactivate pcStore
UI -> CTRL : addTestParameter(testParameter)
activate CTRL
CTRL -> pStore : tp = getTestParameter(testParameter)
activate pStore
deactivate pStore
CTRL -> Test : tp = addTestParameter(parameter)
activate Test
deactivate Test
CTRL--> UI : ok
UI--> SC : added with success
deactivate Test
deactivate CTRL
end loop
end loop
UI --> SC  : Requests data(nhsCode)
deactivate UI

SC -> UI : types requested data
activate UI

UI -> CTRL : generateTestCode()
activate CTRL

CTRL -> Store : generateTestCode()
deactivate CTRL
activate Store





UI -> CTRL : createTest()
activate CTRL
deactivate Store
CTRL -> Company : testStore = getTestStore()

activate Company
deactivate Company
CTRL -> Store : test = createTest(testType, testCategory, testParameter,nhsCode, testCode)
activate Store

Store --> Test : createTest(testType, testCategory, testParameter,nhsCode, testCode)

activate Test
deactivate Store
deactivate Test

CTRL -> Store : validateTest(test)
activate Store
deactivate Store
deactivate CTRL

UI --> SC : Shows the data and requests a confirmation
deactivate UI

SC -> UI : Confirms the data
activate UI

UI -> CTRL : saveTest()
activate CTRL

CTRL -> Store : saveTest(test)
deactivate CTRL
activate Store

Store-> Store: validateTest()
activate Store
deactivate Store
Store-> Store: addTest()
activate Store
deactivate Store
deactivate Store
deactivate CTRL

UI --> SC: Informs operation success.
deactivate UI
deactivate SC

@enduml
