@startuml
skinparam classAttributeIconSize 0

package UI {
class NewProductOrderUI {
}
}

package Controller{
class NewProductOrderController {

}
}

package Order <<Aggregate>>{

entity Product <<Entity>> <<Root>>
entity ProductDescription <<Entity>>
entity PriceTable <<Entity>>
entity SalesRegion <<Entity>>
entity ShoppingCart <<Entity>>
entity PriceItem <<Entity>>
entity Costumer <<Entity>> <<Root>>
entity PaymentMethod <<Entity>>
}


package Category <<Aggregate>> {
    entity Category <<Entity>>

}

NewProductOrderUI ..> NewProductOrderController
NewProductOrderController ..> Category
NewProductOrderController ..>PriceTable
NewProductOrderController ..>ProductDescription
NewProductOrderController ..> Product
NewProductOrderController ..> SalesRegion
NewProductOrderController ..> PriceItem
NewProductOrderController ..> ShoppingCart
NewProductOrderController ..>Costumer
NewProductOrderController ..> PaymentMethod

@enduml