@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Client {
  -String name
  -String gender
  -String ccn
  -String nhsn
  -LocalDate birthDate
  -String tin
  -String phoneNumber
  -Email email
}

class Test {
  -testcode
  -nhsCode
  -createdAt
}

'Attributes and Methods for Class LabOrder'
class LabOrder {
ccn
testType
}

class TestParameterResult{
}

class Sample {
  -code
}


'Attributes for Class ClinicalAnalysisLaboratory'
class ClinicalAnalysisLaboratory {
laboratoryId
}

'Attributes and Methods for Class Company'
class Company {
designation
}

'Attributes and Methods for Class Test Type'
class TestType {
designation
collectingMethod
code
}

'Attributes and Methods for Class Parameter'
class Parameter {
code
shortName
description
}

class ParameterCategory {
code
nhsId
description
}

class MedicalLabTechnician {

}

Company "1" -- "*" Test : performs >
Company "1" -- "*" Client : has >
LabOrder "1"  -- "1" Test : originates >
MedicalLabTechnician "1" -- "*" Test : registers >
ClinicalAnalysisLaboratory "1" -- "*" Test : performs >
Test "1" -- "1" TestParameterResult : has >
Test "1" -- "1" Sample : uses >
Test "*" -- "1" TestType : is of >
Test "*" -- "1" Client: requested by >
Test "*" -- "1..*" Parameter : requests analysis of >
Test "*" -- "1..*" ParameterCategory : requests analysis of >

@enduml