@startuml
autonumber
'hide footbox
actor "Sales Clerck" as SC
participant ":ViewCatalogUI" as UI
participant ":ViewCatalogController" as CTRL
participant ":Category" as Categ
participant ":Product" as Prod
participant ":Order" as Order
participant ":Costumer" as Costumer
participant ":ShoppingCart" as ShopCa
participant ":ShippingMethod" as SM
participant ":PaymentMethod" as PM
activate SC

SC -> UI : starts to create new product's order for a given costumer
activate UI

UI --> SC : shows list of costumers
deactivate UI

SC -> UI : types the chosen costumer's id
activate UI
loop until exits
loop until exits
UI --> SC : asks for a field(category,description, brand..)to filter the catalog
deactivate UI

SC -> UI : types the field
activate UI

end loop
UI --> SC : shows list of products and asks to choose how to order the list (by name or price)
deactivate UI

SC -> UI : chooses how to order
activate UI

UI --> SC : shows list of products and asks for the barcode
deactivate UI

SC -> UI : types the chosen product's barcode
activate UI

UI --> SC :shows all data(code,description,brand,category,price)
deactivate UI

SC -> UI : check product's stock
activate UI
UI --> SC : Shows available stock
deactivate UI

alt if there is stock
SC -> UI : adds product to shopping cart
activate UI
else if there is not stock

UI --> SC : informs operation failure
deactivate UI
end

end loop

UI --> SC : shows the shopping cart of the costumer
activate UI

UI --> SC : shows price of the order with the shipping
deactivate UI
deactivate UI

SC -> UI : chooses payment method
activate UI

UI --> SC : requests confirmation
deactivate UI
SC -> UI : confirms the data

activate UI
UI --> SC : informs operation success
deactivate UI
deactivate SC

@enduml
