@startuml
autonumber
actor "Sales Clerck" as SC


activate SC
SC -> ":System" : starts to create new products order
activate ":System"

":System" --> SC : shows list of costumers
deactivate ":System"

SC -> ":System" : types the chosen costumer's id
activate ":System"

":System" --> SC : shows list of categories
deactivate ":System"

SC -> ":System" : chooses the category
activate ":System"

loop until the sales clerck chooses to exit
":System" --> SC : shows list of subcategories
deactivate ":System"


SC -> ":System" : chooses subcategories
activate ":System"

end loop



":System" --> SC :shows all data and requests confirmation
deactivate ":System"
SC -> ":System" : confirms the data

activate ":System"
":System" --> SC : informs operation success
deactivate ":System"
deactivate SC

@enduml