@startuml
entity Order <<Entity>> <<Root>>

object LineOrder <<Value Object>>

entity PriceTable <<Entity>>

entity SalesRegion <<Entity>>

entity Costumer <<Entity>> <<Root>>

entity PriceTable <<Entity>>

entity PriceTable <<Entity>>

PriceTable --- "1" PriceTableID: >
PriceTable --- "1" SalesRegion: >
Costumer --- "1" CostumerID : has >
Product --- "1" ProductItem: becomes >
ProductItem --- "1" Quantity: has >
PriceItem --- Quantity: depends >
ShippingCost --- Weight: depends >
ShippingCost --- Volume: depends >
Costumer "1" -- "1..*" Order: orders >
ShoppingCart --- "1..*" ProductItem: has >
Order --- "1" OrderID : >
Order --- "1" DateTime : >
Order --- "1" Status : has >
Order --- "1" PaymentMethod : has >
Order --- "1" ShippingMethod : has >
ShippingCost --- "1" SalesRegion: depends >
ShippingMethod--- "1" ShippingCost: has >
Product --- "1" Weight: has >
LineOrder -- "1" Price: has >
LineOrder --- "1" Order: >
LineOrder --- "1" ProductItem: has >
PriceOrder --- Order: depends >
PriceOrder --- ShippingCost: depends >




@enduml