@startuml
skinparam classAttributeIconSize 0

package UI {
class RegisterTestUI {
}
}

package Controller{
class RegisterTestController {
  +createTest(testType,testCategory,testParameter, nhsCode,testCode, createdAt)
  +saveTest()
  +validateTest()
  +getTest()
}
}

package Domain {

class Test {
  -testType
  -testCategory
  -testParameter
  -createdAt
  -nhsCode
  +getTestType()
  +getTestCategory()
  +getTestParameter()
  +getNhsCode()
  +getCreatedAt()
  +getTestCode()
  +Test()
}


class TestStore{
   +createTest()
   +validate(test)
   +saveTest(test)
    +addSample()
   +getTestParameter()
   +getTestMap()
   +getTestList()
   +loadTestsListFromFile()
   +saveTestsListToFile()
   -getTestCode()
}

class TestTypeStore{
   +getTestTypeList()

}

class ParameterStore{
   +getParameterList()

}
class ParameterCategoryStore{
   +getParameterCategoryList()

}
class ClientStore{
   +getClientsList()

}


class Company{
   -designation
   +getTestStore()
   +getTestTypeStore()
   +getParameterStore()
    +getParameterCategoryStore()
    +getClientsStore()
}
}

RegisterTestUI ..> RegisterTestController
RegisterTestController ..> Test
RegisterTestController ..>Company
Company "1" --> "1" TestStore : uses
Company "1" --> "1" TestTypeStore : uses
Company "1" --> "1" ParameterStore : uses
Company "1" --> "1" ParameterCategoryStore : uses
Company "1" --> "1" ClientStore : uses
RegisterTestController ..> TestStore
RegisterTestController ..> TestTypeStore
RegisterTestController ..> ParameterStore
RegisterTestController ..> ParameterCategoryStore
RegisterTestController ..> ClientStore
TestStore"1" --> "*" Test: knows
TestTypeStore"1" --> "*" Test: knows
ParameterStore"1" --> "*" Test: knows
ParameterCategoryStore"1" --> "*" Test: knows
ClientStore "1" --> "*" Test: knows
@enduml