@startuml
autonumber
actor "Sales Clerck" as SC

activate SC
SC -> ":System" : starts to create new product's order for a given costumer
activate ":System"

":System" --> SC : shows list of costumers
deactivate ":System"

SC -> ":System" : types the chosen costumer's id
activate ":System"
loop until exits
":System" --> SC : asks for a field(category,description, brand..)to filter the catalog
deactivate ":System"

SC -> ":System" : types the field
activate ":System"

":System" --> SC : shows list of products and asks to choose how to order the list (by name or price)
deactivate ":System"

SC -> ":System" : chooses how to order
activate ":System"

":System" --> SC : shows list of products and asks for the id
deactivate ":System"

SC -> ":System" : types the chosen product's id

activate ":System"

":System" --> SC : creates the lineOrder
deactivate ":System"

SC -> ":System" : adds product to the lineOrder

activate ":System"
end loop;

":System" --> SC : shows price of the order with the shipping and sales region

deactivate ":System"
SC -> ":System" : chooses payment method
activate ":System"

":System" --> SC :shows all data and requests confirmation

deactivate ":System"

SC -> ":System" :confirms the data
activate ":System"

":System" --> SC : informs operation success
deactivate ":System"
deactivate SC

@enduml