@startuml
autonumber
'hide footbox
actor "Sales Manager" as SM
participant "StatisticalReportUI" as UI <<presentation>>
participant "StatisticalReportController" as CTRL <<application>>
participant "SurveyService" as SERV <<application>>
participant "AnswerService" as ASERV <<application>>
participant "survey:Survey" as Survey <<domain>>
database "SurveyRepository" as SR <<repository>>
database "AnswerRepository" as AR <<repository>>
participant "EvalVisitorReport" as V <<visitor>>


activate SM
SM -> UI : Starts to see surveys available to make statistical report
activate UI

UI -> CTRL : showSurveysAnswered()
activate CTRL


CTRL -> SERV : showSurveysAnswered()

activate SERV
SERV -> SR : findSurveys()
activate SR
SR --> SERV : List<Survey>
deactivate SR
SERV --> CTRL : List<SurveyDTO>
deactivate SERV
CTRL --> UI : List<SurveyDTO>
deactivate CTRL
UI --> SM : List<SurveyDTO>
deactivate UI


SM -> UI : Chooses SurveyID
activate UI
UI -> CTRL : calculateUniverse(SurveyID)
activate CTRL
CTRL -> ASERV : calculateUniverse(SurveyID)
activate ASERV
note right AR #CCE2CB
    Each answer has a costumer associated,
    so amount of answers equals
    the equals amounts of customers (universe)
end note
ASERV -> AR : calculateUniverse(SurveyID)

activate AR
AR --> ASERV : universe
deactivate AR

ASERV --> CTRL : universe
deactivate ASERV
CTRL --> UI : universe
deactivate CTRL
UI --> SM : Shows universe

UI -> CTRL : calculatePercentage(SurveyID)
activate CTRL
CTRL -> ASERV : calculatePercentage(SurveyID)
activate ASERV
ASERV -> AR : calculatePercentage(SurveyID)
activate AR
AR --> ASERV : answers
deactivate AR


ASERV --> CTRL : percentage
deactivate ASERV
CTRL --> UI : percentage
deactivate CTRL
UI --> SM : Shows percentage


UI -> CTRL : calculateNumAnswers(SurveyID)
activate CTRL
CTRL -> ASERV : calculateNumAnswers(SurveyID)
activate ASERV
ASERV -> AR : calculateNumAnswers(SurveyID)
activate AR
AR --> ASERV : numAnswers
deactivate AR

ASERV --> CTRL : numAnswers
deactivate ASERV
CTRL --> UI : numAnswers
deactivate CTRL
UI --> SM : Shows numAnswers


UI -> CTRL : getStatisticalReport(SurveyID)
activate CTRL
CTRL -> SERV : getStatisticalReport(SurveyID)
deactivate CTRL
activate SERV

SERV -> Survey : getStatisticalReport()
activate Survey
deactivate SERV
note right V #CCE2CB
    Visitor validates every answer,
    and calculates the statistics for report
end note
Survey -> V : create

activate V
deactivate Survey
V -> V : visitSingleChoice()
V -> V : visitMultipleChoice()
V -> V : statisticSingleChoice()
V -> V : statisticsMultipleChoice()
V --> UI : statistics
deactivate V
UI --> SM : Shows statistics
deactivate UI



deactivate SM



@enduml