@startuml
autonumber
actor "Sales Clerck" as SC

activate SC

SC -> ":System" : Starts to specify a new product for sale
activate ":System"

":System" --> SC : Requests data (Brand, description, price...)
deactivate ":System"

SC -> ":System" : Types requested data
activate ":System"

":System" --> SC :Shows all data and requests confirmation
deactivate ":System"

SC -> ":System" : Confirms the data

activate ":System"
":System" --> SC : Informs operation (in)success
deactivate ":System"

deactivate SC

@enduml