@startuml
autonumber
actor "Sales Clerk" as SC
participant ":SpecifyNewProductUI" as UI
participant ":SpecifyNewProductController" as CTRL
participant ":Product" as Prod

loop
activate SC

SC -> UI : Starts to specify a new product for sale
activate UI

UI --> SC : Requests data (Brand, description, price...)
deactivate UI

SC -> UI : Types requested data
activate UI

UI --> SC :Shows all data and requests confirmation
deactivate UI

SC -> UI : Confirms the data
activate UI

UI --> SC : Informs operation (in)success
deactivate UI

deactivate SC
end loop
database "Database" as DB

@enduml