@startuml
autonumber
actor "Warehouse Employee" as WE

loop
activate WE

WE -> ":System" : Starts to configure an AGV
activate ":System"

":System" --> WE : Requests data (id, short description, model, maximum weight...)
deactivate ":System"

WE -> ":System" : Types requested data
activate ":System"

":System" --> WE :Shows all data and requests confirmation
deactivate ":System"

WE -> ":System" : Confirms the data

activate ":System"
":System" --> WE : Informs operation (in)success
deactivate ":System"

deactivate WE
end loop

@enduml