@startuml
autonumber
actor "Warehouse Employee" as WE
participant ":ConfigureAGVUI" as UI
participant ":ConfigureAGVController" as CTRL
participant ":AGV" as AGV

loop
activate WE

WE -> UI : Starts to specify a new product for sale
activate UI

UI --> WE : Requests data (Brand, description, price...)
deactivate UI

WE -> UI : Types requested data
activate UI

UI --> WE :Shows all data and requests confirmation
deactivate UI

WE -> UI : Confirms the data
activate UI

UI --> WE : Informs operation (in)success
deactivate UI

deactivate WE
end loop
database "Database" as DB

@enduml