@startuml
autonumber
actor "Sales Clerck" as SC

activate SC

SC -> ":System" : Starts to register a new costumer
activate ":System"
opt birthdate, gender, billing and delivering addresses are not mandatory
":System" --> SC : Requests data (name, VAT identifier, email, phone number, birthdate, gender, billing address, delivering address)
deactivate ":System"
end opt


SC -> ":System" : Inserts requested data
activate ":System"

":System" --> SC :shows all data and requests confirmation
deactivate ":System"


SC -> ":System" : confirms the data
activate ":System"
":System" --> SC : Generates costumerID and informs operation success
deactivate ":System"

deactivate SC

@enduml