@startuml
autonumber
'hide footbox
actor "Sales Clerck" as SC
participant ":RegisterCustomerUI" as UI
participant ":RegistrationController" as CTRL
participant ":Customer" as Customer
/'
participant "testStore:TestStore" as Store
participant "clientStore:ClientStore" as cStore
participant ":ReadConfig" as Read
participant ":OrderingByTin" as OBT
participant ":OrderingByName" as OBN
participant "tMapper: TestMapper" as tMapper
participant "cMapper: ClientMapper" as cMapper
participant "test:Test" as Test
participant "lTestsDTO : List <TestDto>" as testDTO
participant "lClientsDTO : List <ClientsDto>" as clientDTO
participant "client:Client" as Client'/

activate SC

SC -> UI : Starts to register a new costumer
activate UI
opt birthdate, gender, billing and delivering addresses are not mandatory
UI --> SC : Requests data (name, VAT identifier, email, phone number, birthdate, gender, billing address, delivering address)
deactivate UI
end opt


SC -> UI : Inserts requested data
activate UI

UI -> CTRL : newCustomer(name, VAT identifier, email, phone number, birthdate, gender, billing address, delivering address)
activate CTRL

CTRL -> Customer** : costumer = create()
deactivate CTRL
UI --> SC :shows all data and requests confirmation
deactivate UI


SC -> UI : confirms the data
activate UI
UI --> SC : Generates costumerID and informs operation success
deactivate UI

deactivate SC







@enduml
