@startuml
autonumber
actor "Warehouse Employee" as WE
participant ":HTTPAjaxRequest" as AJAX
participant ":HTTPmessage" as HTTPM
participant ":WebDashboard" as WEB
participant ":GetAGVController" as CTRL
participant ":AGVRepository" as REPO
participant ":AGV" as AGV

activate WEB
activate CTRL

WEB -> CTRL :getAGVfromDB()

CTRL -> REPO: findAll()

deactivate CTRL
activate REPO

REPO -> CTRL: returns AGV

deactivate REPO
activate CTRL

CTRL -> WEB: returns AGV

deactivate CTRL


WEB -> AJAX: initializes
activate AJAX
AJAX -> AJAX: waiting for GET request
deactivate WEB

@enduml