@startuml
autonumber
actor "Sales Clerck" as SC

activate SC

":System" --> SC : starts defining new category
activate ":System"

SC -> ":System" : Asks for category name
deactivate ":System"

SC -> ":System" : starts to view/search the products catalog
activate ":System"

":System" --> SC :shows all data and requests confirmation
deactivate ":System"
SC -> ":System" : confirms the data

activate ":System"
":System" --> SC : informs operation success
deactivate ":System"

deactivate ":System"
deactivate SC

@enduml