@startuml
autonumber
'hide footbox
actor "Sales Clerck" as SC
participant "DefineCategoryUI" as UI <<presentation>>
participant "DefineCategoryController" as CTRL <<application>>
participant "CategoryBuilder" as CB <<builder>>
participant "category:Category" as Category <<domain>>
participant "PersistenceContext" as PC <<persistence>>
participant "RepositoryFactory" as RF <<factory>>
database "CategoryRepository" as CR <<repository>>


activate SC
SC -> UI : Starts to define a new category
activate UI
UI --> SC : Requests data (alphanumericCode, description)
deactivate UI



SC -> UI : Inserts requested data
activate UI

UI -> CTRL : defineCategory(alphanumericCode, description)
activate CTRL

note right CB #CCE2CB
    CategoryBuilder is used to create an entity of Customer in a valid state
end note

CTRL -> CB : create
CTRL -> CB : withAlphanumericCode(alphanumericCode)

note right CTRL #CCE2CB
    Places rest of category information
end note

CTRL -> CB : createCategory()
activate CB
CB -> Category : create(alphanumericCode, description)
Category -> CB : category

CB -> CTRL : category
deactivate CB

CTRL -> PC : repositories()
activate PC
note right PC #CCE2CB
    can create repository in memory or JPA
end note
PC -> RF : create
PC -> CTRL : factory
deactivate PC



CTRL -> RF : category()
activate RF
RF -> CR : create
RF -> CTRL : categoryRepository
deactivate RF
CTRL -> CR : save(category)
CTRL -> UI : category
deactivate CTRL

UI --> SC :informs operation success
deactivate UI


deactivate SC



@enduml