@startuml
autonumber
actor "Sales Clerck" as SC

activate SC

":System" --> SC : Starts to define a new category
activate ":System"

SC -> ":System" : Requests data (alphanumericCode, description)
deactivate ":System"

SC -> ":System" : Inserts requested data
activate ":System"

":System" --> SC :informs operation success
deactivate ":System"

deactivate SC

@enduml