@startuml
autonumber
'hide footbox

participant BackofficeApp <<client>>
participant "AGVManager" as AM
participant "AGVController" as OS
participant ":PersistenceContext" as PC
participant "AGVManagerServer" as AMS
participant HandleClient <<Thread>>
participant "MessageParser" as MP
participant "SPOMSProtocol" as SP
participant ":RepositoryFactory" as RF
participant ":AGVRepository" as AGVRepo

AM -> AMS : new()

AM -> AMS : start()
activate AMS

AMS -> AMS : accept

BackofficeApp --> AMS: request
activate HandleClient

AMS -> HandleClient : start
deactivate AMS

HandleClient -> MP : parse(request)

MP -> SP : new

HandleClient -> SP : execute
activate SP

SP -> SP : buildResponse

SP --> HandleClient : response
deactivate SP

HandleClient --> AM : response

AM -> OS : updateStatus()
activate OS

OS -> PC : repositories()
activate PC
deactivate OS

PC -> RF : create()
activate RF
deactivate PC

RF -> AGVRepo : create()
deactivate RF
activate AGVRepo


HandleClient --> BackofficeApp : response
deactivate HandleClient







@enduml
