@startuml
autonumber
actor "Customer" as C

activate C
C -> ":System" : starts to create new product's order for a given costumer
activate ":System"

":System" --> C : shows list of costumers
deactivate ":System"

C -> ":System" : types the chosen costumer's id
activate ":System"
loop until exits
":System" --> C : asks for a field(category,description, brand..)to filter the catalog
deactivate ":System"

C -> ":System" : types the field
activate ":System"

":System" --> C : shows list of products and asks to choose how to order the list (by name or price)
deactivate ":System"

C -> ":System" : chooses how to order
activate ":System"

":System" --> C : shows list of products and asks for the id
deactivate ":System"

C -> ":System" : types the chosen product's id

activate ":System"

":System" --> C : shows all data of product
deactivate ":System"

C -> ":System" : adds product to the shopping cart

activate ":System"
end loop;


":System" --> C :shows all data and informs operation success

deactivate ":System"
deactivate C

@enduml