@startuml
autonumber
actor "Customer" as PM

activate PM
PM -> ":System" : aks to see the questionnaires
activate ":System"

":System" --> PM : shows the questionnaires
deactivate ":System"

PM -> ":System" : chooses the questionnaire to answer
activate ":System"

":System" --> PM : shows questions
deactivate ":System"

PM -> ":System" : chooses if wants to answer the optional questions
activate ":System"
":System" --> PM : shows questions to answer
deactivate ":System"
PM -> ":System" : answers the questions
activate ":System"

":System" --> PM : answers are stored in a .txt
deactivate ":System"

deactivate ":System"
deactivate PM

@enduml