@startuml
autonumber
actor "Sales Manager" as SM
participant ":GrammarUI" as UI
participant ":TextFile" as TF
participant ":GrammarLexer" as GL
participant ":GrammarParser" as GP
participant ":ParseTree" as PS


activate SM

SM -> UI : Start to create a new questionnaire
activate UI

UI -> TF : getFile
activate TF

deactivate TF

UI --> SM : saves the file
deactivate UI

SM -> UI : asks to validate the grammar of questionnaire
activate UI

UI -> GL : analise()
deactivate TF

activate GL
GL -> GP : analise by tokens()
deactivate GL
activate GP
GP -> PS : create()
activate PS
deactivate GP

deactivate PS
UI --> SM : shows all data and request confirmation
deactivate UI



SM -> UI : confirms the data

activate UI
UI --> SM : informs operation success
deactivate UI

deactivate UI
deactivate SM

@enduml