@startuml
autonumber
actor "Sales Manager" as SM
participant ":CreateNewQuestionnaireUI" as UI
participant ":CreateNewQuestionnaireController" as CTRL
participant "TextFile" as TF
participant ":FormGrammarLexer" as GL
participant ":GrammarParser" as GP
participant ":ParseTree" as PS


activate SM

SM -> UI : Start to create a new questionnaire
activate UI

UI -> SM : Asks for the file path
deactivate UI

SM -> UI : Inserts file path
activate UI

UI -> CTRL : getFilePath
activate CTRL

CTRL -> TF : getFilePath
activate TF

deactivate TF

CTRL -> GL : sends path
activate GL
deactivate GL


CTRL -> GL : validate()
deactivate TF
deactivate CTRL

activate GL
GL -> GP : analise by tokens()
deactivate GL
activate GP

GP -> PS : create()
activate PS
deactivate GP

deactivate PS

UI --> SM : informs operation (in)success
deactivate UI

deactivate UI
deactivate SM

@enduml