@startuml
autonumber
'hide footbox
actor "Receptionist" as RECP

participant ":RegisterClientUI" as UI
participant ":RegisterClientController" as CTRL
participant ":Company" as Company
participant "store: ClientStore" as Store
participant "client: RegisterClient" as client
participant "PasswordGenerator" as Pass
participant "Email" as email
participant " userStore" as userStore

activate RECP
RECP -> UI : Starts to register a new client
activate UI
opt user chooses to type the sex or not
UI --> RECP : requests client data (name, sex, phoneNumber, birthDate, tin,ccn,nhsn, email)
end opt
deactivate UI
RECP -> UI : types requested data
activate UI
UI -> CTRL : registerClient (name, sex, phoneNumber, birthDate, tin,ccn,nhsn, email)
activate CTRL
CTRL --> Company : store = getClientStore()
activate Company
deactivate Company
CTRL -> Store : client = registerClient (name, sex, phoneNumber, birthDate, tin,ccn,nhsn, email)
activate  Store
Store --> client *: registerClient(name, sex, phoneNumber, birthDate, tin,ccn,nhsn, email)
deactivate Store
CTRL -> Store : validateClient (client)
activate Store
deactivate Store
deactivate CTRL
deactivate Company
UI --> RECP : Shows all data and requests confirmation
deactivate UI
RECP -> UI : Confirms the data
activate UI
UI -> CTRL : saveClient()
activate CTRL
CTRL -> Store : saveClient(client)
deactivate CTRL
activate Store
Store -> Store: validateClient(client)
activate Store
deactivate Store
Store -> Store: add  Client(client)
activate Store
deactivate Store
deactivate Store
deactivate CTRL

deactivate Store

UI -> email : getEmail()
activate email
deactivate email
activate "Pass"
Pass -> Pass : finalPass = generatePassword()
UI -> Pass : getFinalPassword()
deactivate "Pass"

UI -> userStore : create(name, email.getEmail(), pass.getFinalPassword())
UI -> userStore : add(user)



UI --> RECP: createAnsSendPasswordForNewClient()




deactivate Company
UI --> RECP: informs operation (in)success
deactivate CTRL
deactivate UI
deactivate RECP


@enduml