@startuml
skinparam classAttributeIconSize 0

package UI {
class ViewCatalogUI {
}
}

package Controller{
class ViewCatalogController {

}
}

package Order <<Aggregate>>{

entity Product <<Entity>> <<Root>> {
- ProductDescription
}
entity PriceTable <<Entity>>
entity SalesRegion <<Entity>>
}


package Category <<Aggregate>> {
    entity Category <<Entity>>

}

ViewCatalogUI ..> ViewCatalogController
ViewCatalogController ..> Category
ViewCatalogController ..>PriceTable

ViewCatalogController ..> Product

ViewCatalogController ..> SalesRegion


@enduml