@startuml
autonumber
'hide footbox
actor "Sales Clerck" as SC
participant ":ViewCatalogUI" as UI
participant ":ViewCatalogController" as CTRL
participant ":Category" as Categ
participant ":Product" as Prod

activate SC

SC -> UI : starts to view/search the products catalog
activate UI
loop until exits
UI --> SC :asks for a field(category,description, brand..)to filter the catalog
deactivate UI



SC -> UI : types the field
activate UI

end loop


UI --> SC : shows list of products and asks to choose how to order the list (by name or price)
deactivate UI



SC -> UI : chooses how to order
activate UI

UI --> SC : shows list of products and asks for the barcode
deactivate UI

SC -> UI : types the chosen product's barcode
activate UI



UI --> SC :shows all data(code,description,brand,category,price)and requests confirmation
deactivate UI
SC -> UI : confirms the data

activate UI
UI --> SC : informs operation success
deactivate UI

deactivate UI
deactivate SC

@enduml
